### ISSUE TITLE
How could I disable and skip the trimmomatic step?

### ISSUE THREAD

**Issue by coralzhang** [abaizan/kodoja#33]
How could I disable and skip the trimmomatic step?

**Comment by peterjc** [comment]
Simple answer, provide FASTA not FASTQ as input:

https://github.com/abaizan/kodoja/blob/kodoja-v0.0.9/diagnosticTool_scripts/kodoja_search.py#L148

Beyond that you could try faking it with relaxed minimum length and an empty adapters file, but ultimately, you would have to modify the code. See also:

https://github.com/abaizan/kodoja/blob/kodoja-v0.0.9/diagnosticTool_scripts/diagnostic_modules.py#L134

**Comment by coralzhang** [comment]
Thanks!
