### ISSUE TITLE
Species sequences and Genus sequences in virus_table.txt

### ISSUE THREAD

**Issue by coralzhang** [abaizan/kodoja#35]
Hi, I would like to know what exactly are these two numbers counting?

**Comment by peterjc** [comment]
Does the discussion on #10 or the documentation in the Galaxy wrapper help?

https://github.com/abaizan/kodoja_galaxy/blob/master/kodoja_search.xml#L122

**Comment by coralzhang** [comment]
The help page mentioned

> The counts in columns 6 and 7 are for reads assigned to that genus, but not to any species within it.

But shouldn't a genus be comprised of species, i.e., how come a sequence is aligned to a genus but not to a species in this genus?

**Comment by coralzhang** [comment]
Plus, is there any explanation on how well is the hit for one read? For example, say my read length is 30, does a hit mean all 30 bp matches? How could I tune this?

**Comment by peterjc** [comment]
That number is reads mapped to a genus (eg *Homo*) but not to any particular species (eg *Homo sapiens*).

**Comment by coralzhang** [comment]
I thought that one determines that a read maps to a genus because you think that it maps to a species in the genus.
