### ISSUE TITLE
Kodoja_build.py to update genomes

### ISSUE THREAD

**Issue by mariferrarini** [abaizan/kodoja#41]
Hi,

I was wondering if it's possible to add new genomes to the kodoja_db bypassing the ncbi download everytime.
Let me explain:
I already have my kodoja_db/ folder built and functional with viruses. However, if I run the kodoja_build.py again to add a new genome with "-e"/"-x" parameters, will the script try download  the entire refseq genomes for the viruses?

Thank you very much,
Sincerely, 
Mariana.

**Comment by mariferrarini** [comment]
Sorry for the multiple questions,
 
But also on the same subject, how to I add more than one custom genome to the kodoja_build.py and more than one file per genome?
I tried to add three genomes, two of them contained .fna.gz and .faa.gz files, so I used -e/-x more than once in the command line and the script only kept the last input file given.

Thank you.

**Comment by peterjc** [comment]
There's an example using three genome files here:

https://github.com/abaizan/kodoja/blob/kodoja-v0.0.10/test/test_script.sh#L132

Note the use of ``-n`` or ``--no_download`` to avoid re-downloading.

Does that answer this?

**Comment by mariferrarini** [comment]
Yes, 
That covers everything, thank you very much.
